ALTER TABLE quotations
ADD COLUMN sent_at TIMESTAMP
WITH
    TIME ZONE NULL,
ADD COLUMN accepted_at TIMESTAMP
WITH
    TIME ZONE NULL,
ADD COLUMN rejected_at TIMESTAMP
WITH
    TIME ZONE NULL,
ADD COLUMN converted_at TIMESTAMP
WITH
    TIME ZONE NULL;